### ISSUE TITLE
go get issue

### ISSUE THREAD

**Issue by geraldstanje** [icza/gowut#8]
Hi,

i get this error:
```
go get -u github.com/icza/gowut
package github.com/icza/gowut
	imports github.com/icza/gowut: no buildable Go source files in /Users/geri/Work/gopath
```

**Comment by icza** [comment]
You're right. I fixed the package to be used in the README. Just use the following command:

go get -u github.com/icza/gowut/gwu

**Comment by geraldstanje** [comment]
thanks!

what are the plans for gowut?

**Comment by icza** [comment]
Currently there are no plans. I developed it 2 years ago.

Originally I used code.google.com for hosting, but since it is discontinued, I migrated it to github.com and fixed issues in the process.

It is working fine, but for me to continue developing it, the project would need more interest.

To get a feeling of what you can do, go get the showcase package and run it. It is a "web" demo developed using gowut itself:

go get -u github.com/icza/gowut/examples/showcase

And starting it:

go run src/github.com/icza/gowut/examples/showcase/showcase.go

It auto-opens itself in your default browser. Also note that gowut is extensible. You can create your own custom components beside the ones provided by the project.

**Comment by geraldstanje** [comment]
can you plot graphs, diagrams with gowut?

did you look at other web ui platforms which has been used for java, c++, ...?

**Comment by icza** [comment]
No, current version does not support graphs and diagrams.

**Comment by geraldstanje** [comment]
that would be cool to see :)

**Comment by geraldstanje** [comment]
some feedback to gowut:
http://noeffclue.blogspot.co.at/2013/06/proposal-for-gui-toolkit-for-go.html
